export type ItemType = 'consumable' | 'material' | 'gift' | 'key' | 'special';

export type ItemRarity = 'common' | 'rare' | 'special';

export type GameItem = {
  id: string;
  name: string;
  description: string;
  type: ItemType;
  stackable: boolean;
  usable: boolean;
  giftable: boolean;
  rarity?: ItemRarity;
  icon: string;
  tags?: string[];
};

export const gameItems: Record<string, GameItem> = {
  warm_bread: {
    id: 'warm_bread',
    name: '温热面包',
    description: '刚出炉不久，纸袋边缘还带着一点麦香和热气。',
    type: 'consumable',
    stackable: true,
    usable: false,
    giftable: false,
    rarity: 'common',
    icon: '🥖',
    tags: ['早餐', '补给'],
  },
  berry_milk: {
    id: 'berry_milk',
    name: '雾莓牛奶',
    description: '淡紫色的瓶装牛奶，喝前需要轻轻摇三下。',
    type: 'consumable',
    stackable: true,
    usable: false,
    giftable: false,
    rarity: 'common',
    icon: '🥛',
    tags: ['饮品', '雾莓'],
  },
  simple_candle: {
    id: 'simple_candle',
    name: '小蜡烛',
    description: '适合夜读、写信，或者假装自己很有仪式感。',
    type: 'key',
    stackable: true,
    usable: false,
    giftable: false,
    rarity: 'common',
    icon: '🕯️',
    tags: ['照明', '小屋'],
  },
  note_paper_pack: {
    id: 'note_paper_pack',
    name: '便签纸包',
    description: '一叠手感很好的小纸片，能承受轻微魔力涂改。',
    type: 'key',
    stackable: true,
    usable: false,
    giftable: false,
    rarity: 'common',
    icon: '📝',
    tags: ['记录', '学习'],
  },
  storage_box: {
    id: 'storage_box',
    name: '旧木收纳盒',
    description: '盖子有点松，但很适合收纳那些暂时不知道用途的小东西。',
    type: 'special',
    stackable: true,
    usable: false,
    giftable: false,
    rarity: 'common',
    icon: '🧰',
    tags: ['收纳', '小屋'],
  },
  sweet_water: {
    id: 'sweet_water',
    name: '小甜水',
    description: '市集同款，颜色可疑，但摊主保证“至少今天没问题”。',
    type: 'consumable',
    stackable: true,
    usable: false,
    giftable: false,
    rarity: 'common',
    icon: '🧋',
    tags: ['饮品', '市集'],
  },
  cleaning_cloth: {
    id: 'cleaning_cloth',
    name: '柔软抹布',
    description: '适合擦桌面、杯子，以及某些不肯承认自己落灰的魔法道具。',
    type: 'key',
    stackable: true,
    usable: false,
    giftable: false,
    rarity: 'common',
    icon: '🧽',
    tags: ['清洁', '日用'],
  },
  pocket_snack: {
    id: 'pocket_snack',
    name: '口袋零食',
    description: '小小一包，适合出门前塞进口袋，防止意志力突然塌方。',
    type: 'consumable',
    stackable: true,
    usable: false,
    giftable: false,
    rarity: 'common',
    icon: '🍪',
    tags: ['零食', '便携'],
  },
  mistberry: {
    id: 'mistberry',
    name: '雾莓',
    description: '雾气里成熟的小浆果，酸甜味会在舌尖慢慢散开。',
    type: 'material',
    stackable: true,
    usable: false,
    giftable: false,
    rarity: 'common',
    icon: '🫐',
    tags: ['材料', '魔药', '雾莓', '基础'],
  },
  moon_grass_powder: {
    id: 'moon_grass_powder',
    name: '月草粉',
    description: '磨得很细的浅银色草粉，瓶口会沾上一点月光似的亮。',
    type: 'material',
    stackable: true,
    usable: false,
    giftable: false,
    rarity: 'rare',
    icon: '🌙',
    tags: ['材料', '魔药', '草本', '基础'],
  },
  empty_potion_bottle: {
    id: 'empty_potion_bottle',
    name: '空药瓶',
    description: '适合装入第一份像样的药剂，也适合先摆在桌上壮胆。',
    type: 'material',
    stackable: true,
    usable: false,
    giftable: false,
    rarity: 'common',
    icon: '🧪',
    tags: ['材料', '魔药', '瓶罐', '基础'],
  },
  dried_mint_leaf: {
    id: 'dried_mint_leaf',
    name: '干薄荷叶',
    description: '晒干后仍有清凉香气，能让过分沉重的配方轻一点。',
    type: 'material',
    stackable: true,
    usable: false,
    giftable: false,
    rarity: 'common',
    icon: '🌿',
    tags: ['材料', '魔药', '草本', '基础'],
  },
  tiny_crystal_salt: {
    id: 'tiny_crystal_salt',
    name: '细晶盐',
    description: '颗粒很细，偶尔会在纸包里发出轻轻的碎光声。',
    type: 'material',
    stackable: true,
    usable: false,
    giftable: false,
    rarity: 'common',
    icon: '🧂',
    tags: ['材料', '魔药', '晶盐', '基础'],
  },
  soft_mushroom_cap: {
    id: 'soft_mushroom_cap',
    name: '软蘑菇伞',
    description: '森林边缘常见的小蘑菇，伞面软得像一小块湿云。',
    type: 'material',
    stackable: true,
    usable: false,
    giftable: false,
    rarity: 'common',
    icon: '🍄',
    tags: ['材料', '魔药', '森林', '基础'],
  },
  glow_wick: {
    id: 'glow_wick',
    name: '微光灯芯',
    description: '不用点燃也会微微发亮，常被放进需要稳定光源的配方。',
    type: 'material',
    stackable: true,
    usable: false,
    giftable: false,
    rarity: 'rare',
    icon: '🕯️',
    tags: ['材料', '魔药', '灯芯', '基础'],
  },
  clear_spring_water: {
    id: 'clear_spring_water',
    name: '清泉水',
    description: '装在小瓶里的清澈泉水，摇晃时像把早晨也带了进去。',
    type: 'material',
    stackable: true,
    usable: false,
    giftable: false,
    rarity: 'common',
    icon: '💧',
    tags: ['材料', '魔药', '清水', '基础'],
  },
  sweet_water_pair: {
    id: 'sweet_water_pair',
    name: '小甜水双瓶装',
    description: '两瓶颜色都很可疑的小甜水，适合带去一场不太正式的闲聊。',
    type: 'gift',
    stackable: true,
    usable: false,
    giftable: true,
    rarity: 'common',
    icon: '🧋',
    tags: ['礼物', '饮品', '甜食', '心意'],
  },
  glowing_mint_candy: {
    id: 'glowing_mint_candy',
    name: '发光薄荷糖',
    description: '含在嘴里会凉很久，纸包边缘还透着一点点绿光。',
    type: 'gift',
    stackable: true,
    usable: false,
    giftable: true,
    rarity: 'rare',
    icon: '🍬',
    tags: ['礼物', '甜食', '薄荷', '莉莉丝'],
  },
  old_poetry_book: {
    id: 'old_poetry_book',
    name: '旧诗集',
    description: '封面有些旧，里面却夹着几句很适合雨天读的诗。',
    type: 'gift',
    stackable: true,
    usable: false,
    giftable: true,
    rarity: 'rare',
    icon: '📖',
    tags: ['礼物', '书本', '心意'],
  },
  ribbon_charm: {
    id: 'ribbon_charm',
    name: '缎带护符',
    description: '柔软缎带系着小小护符，看起来比它自己承认的更认真。',
    type: 'gift',
    stackable: true,
    usable: false,
    giftable: true,
    rarity: 'common',
    icon: '🎀',
    tags: ['礼物', '饰品', '护符', '心意'],
  },
  berry_jam_cookie: {
    id: 'berry_jam_cookie',
    name: '雾莓果酱饼干',
    description: '果酱藏在饼干中间，咬开时会露出一点紫红色的甜。',
    type: 'gift',
    stackable: true,
    usable: false,
    giftable: true,
    rarity: 'common',
    icon: '🍪',
    tags: ['礼物', '甜食', '雾莓', '心意'],
  },
  little_glass_bottle: {
    id: 'little_glass_bottle',
    name: '小玻璃瓶',
    description: '透明得很乖巧，适合装花、装纸条，或者装一句没说出口的话。',
    type: 'gift',
    stackable: true,
    usable: false,
    giftable: true,
    rarity: 'common',
    icon: '🫙',
    tags: ['礼物', '瓶罐', '饰品', '心意'],
  },
  pressed_flower_card: {
    id: 'pressed_flower_card',
    name: '压花卡片',
    description: '薄薄的卡片里压着小花，像把某个晴天认真保存了下来。',
    type: 'gift',
    stackable: true,
    usable: false,
    giftable: true,
    rarity: 'common',
    icon: '💌',
    tags: ['礼物', '花', '卡片', '心意'],
  },
  star_sugar_box: {
    id: 'star_sugar_box',
    name: '星糖小盒',
    description: '一盒亮晶晶的小糖粒，倒出来时像有人偷藏了一把夜空。',
    type: 'gift',
    stackable: true,
    usable: false,
    giftable: true,
    rarity: 'rare',
    icon: '⭐',
    tags: ['礼物', '甜食', '星糖', '心意'],
  },
};
