import type { GameLocation } from '@/features/game/engine/types';

export const demoLocations: GameLocation[] = [
  {
    id: 'home',
    name: '魔女小屋',
    subtitle: '醒来和休息的地方',
    description: '熟悉的小屋里放着笔记、药草和还没收好的杯子。',
    icon: '🏠',
    backgroundId: 'room_morning',
    entryEventId: 'home_hut',
    tags: ['home', 'rest'],
  },
  {
    id: 'market',
    name: '市集',
    subtitle: '买东西和打听消息',
    description: '摊位、香气和来往的脚步把白天搅得很热闹。',
    icon: '🧺',
    backgroundId: 'market_day',
    entryEventId: 'market_morning',
    tags: ['social', 'shopping'],
  },
  {
    id: 'grocery',
    name: '杂货铺',
    subtitle: '香甜零食和纸笔',
    description: '货架上摆着糖果、空白本子和看起来很会推销的东西。',
    icon: '🛒',
    backgroundId: 'market_day',
    entryEventId: 'grocery_shop',
    tags: ['shopping'],
  },
  {
    id: 'church',
    name: '教堂',
    subtitle: '安静和祈祷',
    description: '长椅、烛火和低声祷词把这里衬得很轻。',
    icon: '⛪',
    backgroundId: 'academy_gate',
    entryEventId: 'church_pray',
    tags: ['story', 'calm'],
  },
  {
    id: 'forest',
    name: '魔物森林',
    subtitle: '草药和雾气',
    description: '树影和潮湿的土地气息让人不太想久留。',
    icon: '🌲',
    backgroundId: 'forest_evening',
    entryEventId: 'monster_forest',
    tags: ['gathering', 'exploration'],
  },
  {
    id: 'bar',
    name: '酒吧',
    subtitle: '夜晚才热闹',
    description: '灯光和笑声只会在入夜后慢慢浮起来。',
    icon: '🍷',
    backgroundId: 'market_day',
    entryEventId: 'bar_night',
    tags: ['social', 'nightlife'],
    openHours: {
      startHour: 20,
      endHour: 6,
    },
  },
];
