import type { GameLocation } from '@/features/game/engine/types';

export const demoLocations: GameLocation[] = [
  {
    id: 'home',
    name: 'Home',
    subtitle: 'The witch hut where the day begins.',
    description: 'Old books, herbs, and unfinished notes are scattered across the room.',
    icon: 'H',
    backgroundId: 'room_morning',
    entryEventId: 'demo_start',
    tags: ['home', 'rest'],
  },
  {
    id: 'market',
    name: 'Market',
    subtitle: 'A place for people, errands, and small encounters.',
    description: 'The air carries spice, paper, and the damp smell of stone after rain.',
    icon: 'M',
    backgroundId: 'market_day',
    entryEventId: 'demo_market',
    tags: ['social', 'shopping'],
  },
  {
    id: 'forest',
    name: 'Forest',
    subtitle: 'Good for gathering and wandering.',
    description: 'Herbs grow deeper in the shade, and it is easy to lose track of the road.',
    icon: 'F',
    backgroundId: 'forest_evening',
    entryEventId: 'demo_hidden',
    tags: ['gathering', 'exploration'],
  },
  {
    id: 'academy',
    name: 'Academy',
    subtitle: 'Magic, study, and social ties.',
    description: 'Footsteps echo under the corridor as new notices appear on the board.',
    icon: 'A',
    backgroundId: 'academy_gate',
    entryEventId: 'demo_vn_morning',
    tags: ['study', 'story'],
  },
  {
    id: 'bar',
    name: 'Bar',
    subtitle: 'A night-only hangout.',
    description: 'A quiet bar that comes alive after sunset.',
    icon: 'B',
    backgroundId: 'market_day',
    entryEventId: 'demo_market',
    tags: ['social', 'nightlife'],
    openHours: {
      startHour: 20,
      endHour: 6,
    },
  },
];
