import type { ProductCategoryId, ShopProduct } from '@/features/game/content/main/shops/types';

export const shopProducts: ShopProduct[] = [
  {
    id: 'warm_bread',
    name: '温热面包',
    description: '刚出炉不久，纸袋边缘还带着一点麦香和热气。',
    category: 'daily',
    price: 8,
    currency: 'gold',
    itemId: 'warm_bread',
    icon: '🥖',
    tags: ['早餐', '补给'],
  },
  {
    id: 'berry_milk',
    name: '雾莓牛奶',
    description: '淡紫色的瓶装牛奶，喝前需要轻轻摇三下。',
    category: 'daily',
    price: 12,
    currency: 'gold',
    itemId: 'berry_milk',
    icon: '🥛',
    tags: ['饮品', '雾莓'],
  },
  {
    id: 'simple_candle',
    name: '小蜡烛',
    description: '适合夜读、写信，或者假装自己很有仪式感。',
    category: 'daily',
    price: 10,
    currency: 'gold',
    itemId: 'simple_candle',
    icon: '🕯️',
    tags: ['照明', '小屋'],
  },
  {
    id: 'note_paper_pack',
    name: '便签纸包',
    description: '一叠手感很好的小纸片，能承受轻微魔力涂改。',
    category: 'daily',
    price: 15,
    currency: 'gold',
    itemId: 'note_paper_pack',
    icon: '📝',
    tags: ['记录', '学习'],
  },
  {
    id: 'storage_box',
    name: '旧木收纳盒',
    description: '盖子有点松，但很适合收纳那些暂时不知道用途的小东西。',
    category: 'daily',
    price: 30,
    currency: 'gold',
    itemId: 'storage_box',
    icon: '🧰',
    tags: ['收纳', '小屋'],
  },
  {
    id: 'sweet_water',
    name: '小甜水',
    description: '市集同款，颜色可疑，但摊主保证“至少今天没问题”。',
    category: 'daily',
    price: 12,
    currency: 'gold',
    itemId: 'sweet_water',
    icon: '🧋',
    tags: ['饮品', '市集'],
  },
  {
    id: 'cleaning_cloth',
    name: '柔软抹布',
    description: '适合擦桌面、杯子，以及某些不肯承认自己落灰的魔法道具。',
    category: 'daily',
    price: 9,
    currency: 'gold',
    itemId: 'cleaning_cloth',
    icon: '🧽',
    tags: ['清洁', '日用'],
  },
  {
    id: 'pocket_snack',
    name: '口袋零食',
    description: '小小一包，适合出门前塞进口袋，防止意志力突然塌方。',
    category: 'daily',
    price: 18,
    currency: 'gold',
    itemId: 'pocket_snack',
    icon: '🍪',
    tags: ['零食', '便携'],
  },
];

export function getProductsByCategory(category: ProductCategoryId): ShopProduct[] {
  return shopProducts.filter((product) => product.category === category);
}
