import type { ProductCategoryId, ShopProduct } from '@/features/game/content/main/shops/types';

export const shopProducts: ShopProduct[] = [
  {
    id: 'warm_bread',
    name: '温热面包',
    description: '刚出炉不久，纸袋边缘还带着一点麦香和热气。',
    category: 'daily',
    price: 8,
    currency: 'gold',
    itemId: 'warm_bread',
    icon: '🥖',
    tags: ['早餐', '补给'],
  },
  {
    id: 'berry_milk',
    name: '雾莓牛奶',
    description: '淡紫色的瓶装牛奶，喝前需要轻轻摇三下。',
    category: 'daily',
    price: 12,
    currency: 'gold',
    itemId: 'berry_milk',
    icon: '🥛',
    tags: ['饮品', '雾莓'],
  },
  {
    id: 'simple_candle',
    name: '小蜡烛',
    description: '适合夜读、写信，或者假装自己很有仪式感。',
    category: 'daily',
    price: 10,
    currency: 'gold',
    itemId: 'simple_candle',
    icon: '🕯️',
    tags: ['照明', '小屋'],
  },
  {
    id: 'note_paper_pack',
    name: '便签纸包',
    description: '一叠手感很好的小纸片，能承受轻微魔力涂改。',
    category: 'daily',
    price: 15,
    currency: 'gold',
    itemId: 'note_paper_pack',
    icon: '📝',
    tags: ['记录', '学习'],
  },
  {
    id: 'storage_box',
    name: '旧木收纳盒',
    description: '盖子有点松，但很适合收纳那些暂时不知道用途的小东西。',
    category: 'daily',
    price: 30,
    currency: 'gold',
    itemId: 'storage_box',
    icon: '🧰',
    tags: ['收纳', '小屋'],
  },
  {
    id: 'sweet_water',
    name: '小甜水',
    description: '市集同款，颜色可疑，但摊主保证“至少今天没问题”。',
    category: 'daily',
    price: 12,
    currency: 'gold',
    itemId: 'sweet_water',
    icon: '🧋',
    tags: ['饮品', '市集'],
  },
  {
    id: 'cleaning_cloth',
    name: '柔软抹布',
    description: '适合擦桌面、杯子，以及某些不肯承认自己落灰的魔法道具。',
    category: 'daily',
    price: 9,
    currency: 'gold',
    itemId: 'cleaning_cloth',
    icon: '🧽',
    tags: ['清洁', '日用'],
  },
  {
    id: 'pocket_snack',
    name: '口袋零食',
    description: '小小一包，适合出门前塞进口袋，防止意志力突然塌方。',
    category: 'daily',
    price: 18,
    currency: 'gold',
    itemId: 'pocket_snack',
    icon: '🍪',
    tags: ['零食', '便携'],
  },
  {
    id: 'mistberry',
    name: '雾莓',
    description: '雾气里成熟的小浆果，酸甜味会在舌尖慢慢散开。',
    category: 'materials',
    price: 22,
    currency: 'gold',
    itemId: 'mistberry',
    icon: '🫐',
    tags: ['材料', '魔药', '雾莓', '基础'],
  },
  {
    id: 'moon_grass_powder',
    name: '月草粉',
    description: '磨得很细的浅银色草粉，瓶口会沾上一点月光似的亮。',
    category: 'materials',
    price: 32,
    currency: 'gold',
    itemId: 'moon_grass_powder',
    icon: '🌙',
    tags: ['材料', '魔药', '草本', '基础'],
  },
  {
    id: 'empty_potion_bottle',
    name: '空药瓶',
    description: '适合装入第一份像样的药剂，也适合先摆在桌上壮胆。',
    category: 'materials',
    price: 24,
    currency: 'gold',
    itemId: 'empty_potion_bottle',
    icon: '🧪',
    tags: ['材料', '魔药', '瓶罐', '基础'],
  },
  {
    id: 'dried_mint_leaf',
    name: '干薄荷叶',
    description: '晒干后仍有清凉香气，能让过分沉重的配方轻一点。',
    category: 'materials',
    price: 18,
    currency: 'gold',
    itemId: 'dried_mint_leaf',
    icon: '🌿',
    tags: ['材料', '魔药', '草本', '基础'],
  },
  {
    id: 'tiny_crystal_salt',
    name: '细晶盐',
    description: '颗粒很细，偶尔会在纸包里发出轻轻的碎光声。',
    category: 'materials',
    price: 28,
    currency: 'gold',
    itemId: 'tiny_crystal_salt',
    icon: '🧂',
    tags: ['材料', '魔药', '晶盐', '基础'],
  },
  {
    id: 'soft_mushroom_cap',
    name: '软蘑菇伞',
    description: '森林边缘常见的小蘑菇，伞面软得像一小块湿云。',
    category: 'materials',
    price: 35,
    currency: 'gold',
    itemId: 'soft_mushroom_cap',
    icon: '🍄',
    tags: ['材料', '魔药', '森林', '基础'],
  },
  {
    id: 'glow_wick',
    name: '微光灯芯',
    description: '不用点燃也会微微发亮，常被放进需要稳定光源的配方。',
    category: 'materials',
    price: 40,
    currency: 'gold',
    itemId: 'glow_wick',
    icon: '🕯️',
    tags: ['材料', '魔药', '灯芯', '基础'],
  },
  {
    id: 'clear_spring_water',
    name: '清泉水',
    description: '装在小瓶里的清澈泉水，摇晃时像把早晨也带了进去。',
    category: 'materials',
    price: 20,
    currency: 'gold',
    itemId: 'clear_spring_water',
    icon: '💧',
    tags: ['材料', '魔药', '清水', '基础'],
  },
  {
    id: 'sweet_water_pair',
    name: '小甜水双瓶装',
    description: '两瓶颜色都很可疑的小甜水，适合带去一场不太正式的闲聊。',
    category: 'gift',
    price: 28,
    currency: 'gold',
    itemId: 'sweet_water_pair',
    icon: '🧋',
    tags: ['礼物', '饮品', '甜食', '心意'],
  },
  {
    id: 'glowing_mint_candy',
    name: '发光薄荷糖',
    description: '含在嘴里会凉很久，纸包边缘还透着一点点绿光。',
    category: 'gift',
    price: 34,
    currency: 'gold',
    itemId: 'glowing_mint_candy',
    icon: '🍬',
    tags: ['礼物', '甜食', '薄荷', '莉莉丝'],
  },
  {
    id: 'old_poetry_book',
    name: '旧诗集',
    description: '封面有些旧，里面却夹着几句很适合雨天读的诗。',
    category: 'gift',
    price: 48,
    currency: 'gold',
    itemId: 'old_poetry_book',
    icon: '📖',
    tags: ['礼物', '书本', '心意'],
  },
  {
    id: 'ribbon_charm',
    name: '缎带护符',
    description: '柔软缎带系着小小护符，看起来比它自己承认的更认真。',
    category: 'gift',
    price: 42,
    currency: 'gold',
    itemId: 'ribbon_charm',
    icon: '🎀',
    tags: ['礼物', '饰品', '护符', '心意'],
  },
  {
    id: 'berry_jam_cookie',
    name: '雾莓果酱饼干',
    description: '果酱藏在饼干中间，咬开时会露出一点紫红色的甜。',
    category: 'gift',
    price: 30,
    currency: 'gold',
    itemId: 'berry_jam_cookie',
    icon: '🍪',
    tags: ['礼物', '甜食', '雾莓', '心意'],
  },
  {
    id: 'little_glass_bottle',
    name: '小玻璃瓶',
    description: '透明得很乖巧，适合装花、装纸条，或者装一句没说出口的话。',
    category: 'gift',
    price: 36,
    currency: 'gold',
    itemId: 'little_glass_bottle',
    icon: '🫙',
    tags: ['礼物', '瓶罐', '饰品', '心意'],
  },
  {
    id: 'pressed_flower_card',
    name: '压花卡片',
    description: '薄薄的卡片里压着小花，像把某个晴天认真保存了下来。',
    category: 'gift',
    price: 44,
    currency: 'gold',
    itemId: 'pressed_flower_card',
    icon: '💌',
    tags: ['礼物', '花', '卡片', '心意'],
  },
  {
    id: 'star_sugar_box',
    name: '星糖小盒',
    description: '一盒亮晶晶的小糖粒，倒出来时像有人偷藏了一把夜空。',
    category: 'gift',
    price: 62,
    currency: 'gold',
    itemId: 'star_sugar_box',
    icon: '⭐',
    tags: ['礼物', '甜食', '星糖', '心意'],
  },
];

export function getProductsByCategory(category: ProductCategoryId): ShopProduct[] {
  return shopProducts.filter((product) => product.category === category);
}
